### ISSUE TITLE
Contributor's guide. 

### ISSUE THREAD

**Issue by HarryHeights** [Valou3433/blade-player#35]
Hi! I'm glad to see that you are still actively maintaining this project. Great job. Been looking for other ways to add value to the project again after such a long time. And, you know I'm good at creating written content. I looked up the repo again and found no contributor's guide. I think it will be a nice document to have.  Just give the go ahead and I'll get to work right away.
Once again, great job.

**Comment by Valou3433** [comment]
Hi !
Of course you can build a contributor's guide, i did not do it because i had no time but it would be really good.
If you do that, please ask people to feel free to contact me before contributing, about what can be done for the project or anything that could help them writing code.
Valou3433
PS : i'm sorry i did not answer earlier, i'm just really busy at the moment...

**Comment by HarryHeights** [comment]
Oh okay. No qualms.

> If you do that, please ask people to feel free to contact me before contributing, about what can be done for the project or anything that could help them writing code.

I'll do just that.

**Comment by Valou3433** [comment]
Well the document you created is perfect ! Thank you for your time and your work ; i merged it to master and i'm closing this issue...
