### ISSUE TITLE
Option not working while music is on

### ISSUE THREAD

**Issue by Olamatto** [Valou3433/blade-player#8]
#### Expected behavior
The option ought to work perfectly well while playing music.

#### Actual Behavior 
The option button is not working, while playing music on the application. 

#### How to reproduce
- Download and install the application [here](http://valou3433.fr/blade)
- Lunch the application 
- Select the Artist you want
- Select the album
- Click on the song
- Click below on the current song
- Click on the option button

And notice it is not working. 

<hr>

Application version: v 0.5
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/Ug4GhD4yftA

**Comment by Valou3433** [comment]
That is actually the expected behavior, as i did not implement any options for a song (except play/play next/add to queue but these are useless on the current playing song display)...
However i'm implementing options like "add to playlist..." or "add to library" on version 0.6 !
Anyway thanks for the report !

**Comment by Olamatto** [comment]
Ok nice then, we will be looking forward to making the button active.
